<?php

/**
 * @file
 * Contains obfuscate_email_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function obfuscate_email_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the obfuscate_email_field module.
    case 'help.page.obfuscate_email_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Twig Template to obfuscate a field_email') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function obfuscate_email_field_theme() {
  $theme = [
    'field__email' => [
      'base hook' => 'field',
      'template' => 'field--email',
    ],
  ];

  return $theme;
}

/**
 * Implements hook_page_attachments_alter().
 */
function obfuscate_email_field_page_attachments_alter(&$page) {
  $page['#attached']['library'][] = 'obfuscate_email_field/default';
}
